### ISSUE TITLE
Had to add "-I/usr/local/Cellar/glfw/3.3.8/include" to compile

### ISSUE THREAD

**Issue by Unturned3** [zamirmf/OpenGLOnMac#1]
Thanks for this tutorial! I'm following The Cherno's series on OpenGL, and he did not include the following bit:
```
unsigned int VAO;
glGenVertexArrays(1, &VAO); 
glBindVertexArray(VAO);
```
And as a result, nothing rendered on my screen. I'm on MacOS 12.7.1 btw.

Also, I had to add the include paths to the GLFW library to the clang command:
```
clang -o main main.cpp -L/usr/local/lib -lglfw -framework OpenGL -I/usr/local/Cellar/glfw/3.3.8/include
```
Otherwise it complained about not being able to find `GLFW/glfw3.h`

Just wanted to put this here in case anyone else runs into the same issue.

**Comment by zamirmf** [comment]
@Unturned3 Thank you very much for reporting this issue.

It seems that `GLFW` isn't getting installed under `usr/local` anymore.

I have updated the compilation to consider `homebrew` related folders to both headers and libraries files.

This fix has been pushed as part of [this commit](https://github.com/zamirmf/OpenGLOnMac/commit/c4b2c6573db8db046d1138e08614023d38d031d7).
